AWSTemplateFormatVersion: "2010-09-09"

Description: Lambda functions for scanning a few AWS services

# Lambdas for scanning - Done
# Lambda role - Done
# Lambda Invoke config
# S3 bucket for Lambda zip file - Done
# SNS topic + sub - Done
# EventBridge cron job rule - Done

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: awsscan-lambda-bucket

  EventBridgeCron:
    Type: AWS::Events::Rule
    Properties:
      Name: ScanCron
      Description: Lambda cronjob for service scans
      ScheduleExpression: cron(0 16-22 * * ? *)
      Targets: 
        - Arn:
            Fn::GetAtt:
              - "LambdaScan"
              - "Arn"
          Id: "LambdaTarget"

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaScan
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn:
        Fn::GetAtt:
          - "EventBridgeCron"
          - "Arn"

  ScanTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ScanTopic

  ScanSub:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      Endpoint: dpresnjak@iolap.com
      TopicArn: !Ref ScanTopic

  LambdaScan:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: awsscan-lambda-bucket
        S3Key: lambda_function.zip
      Description: AWS scan scan function
      FunctionName: "AWSScanLambda"
      Handler: lambda_function.lambda_handler
      MemorySize: 256
      Role: !GetAtt LambdaIamRole.Arn
      Runtime: python3.9
      Timeout: 60

  LambdaIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: AWSLambdaScan
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "logs:*"
                Resource: "arn:aws:logs:*:*:*"
              - Effect: "Allow"
                Action: [
                  "lambda:ListFunctions",
                  "lambda:GetFunctionConcurrency",
                  "dynamodb:DescribeTable",
                  "dynamodb:ListTables",
                  "lambda:GetFunction",
                  "glue:ListJobs",
                  "glue:GetJob"]
                Resource: "*"
              - Effect: "Allow"
                Action: [
                  "sns:Publish",
                  "logs:CreateLogGroup"]
                Resource: [
                  "arn:aws:sns:us-east-1:*:ScanTopic",
                  "arn:aws:logs:us-east-1:*:*"]
              - Effect: "Allow"
                Action: [
                  "lambda:ListFunctions",
                  "lambda:GetFunctionConcurrency"]
                Resource: "arn:aws:lambda:*:*:function:*"